### ISSUE TITLE
eFormidling craching when used after a data task

### ISSUE THREAD

**Issue by RonnyB71** [Altinn/app-lib-dotnet#105]
### Description of the bug

When eFormidling integration is set up to run after a data task instead of confirmation task the integration crashes if you try to access the pdf data element since the instance being passed on isn't updated with the latest data elements.

### Steps To Reproduce

Create a eFormidling integration and set it up to run after the data task

**Comment by olemartinorg** [comment]
Closing this, as it's marked as done. Re-open if needed, @RonnyB71
