### ISSUE TITLE
Change DAN lookup to run on behalf of the home municipality of the applicant instead of DIHE

### ISSUE THREAD

**Issue by RonnyB71** [Altinn/app-lib-dotnet#107]
### Description

DIHE is an organization representing 16 municipalities. When looking up taxes and income from DAN for an applicant, it is done based on DIHE as a organization. This should be changed to use the municipality of the applicant since they have the implicit legal rights to ask for this information when the applicant fills out the application.

### Additional Information

This can be done by each municipality delegating that right to DIHE and the use of consumer_org claim when requesting the token from maskinporten ref. https://docs.digdir.no/docs/Maskinporten/maskinporten_guide_apikonsument#eksempel-p%C3%A5-bruk--av-altinn

This implies changing the MaskinportenClient implementation as this is currently does not support requesting claims, only scopes.

**Comment by elsand** [comment]
@RonnyB71 @erlendoksvoll 

I've added an issue regarding consumer_org-support in altinn-apiclient-maskinporten. Regarding the DAN integration, there are two distinct options:

1. DIHE is authenticating against DAN
    * A [separate token](https://github.com/data-altinn-no/altinn-apiclient-dan/blob/main/src/Altinn.ApiClients.Dan/Interfaces/IDanClient.cs#L27) will have to be supplied to DAN to be used against FREG/Skatteetaten. 
    * Will require the calling code to get that additional token via https://github.com/Altinn/altinn-apiclient-maskinporten#manual-use-of-tokenservice or similar
    * The municipalities will only have to delegate access to the FREG/Skatteetaten-scopes in Altinn
2. The various municipalities are authenticating against DAN
    * Can [reuse the same token](https://github.com/data-altinn-no/altinn-apiclient-dan/blob/main/src/Altinn.ApiClients.Dan/Interfaces/IDanClient.cs#L60) for both DAN and FREG/Skatteetaten
    * No additional code for getting additional token required in calling code
    * The municipalities will have to delegate both the Skatteetaten/FREG scopes as well as altinn:dataaltinnno/dihe. A delegation scheme will have to be created for altinn:dataaltinnno/dihe
    * Can reuse the same DAN subscription key

"Calling code" can here be either applib or the app code itself. I haven't looked much at either, but if there is some sort of abstraction between the app and DAN in applib, I assume we want the lifting required for getting that additional token to be there, leaving to the app to only instruct which organization number it wants as the consumer_org claim.

**Comment by elsand** [comment]
Support for consumer_org claims is now added in https://www.nuget.org/packages/Altinn.ApiClients.Maskinporten/7.0.0 (was https://github.com/Altinn/altinn-apiclient-maskinporten/issues/11)

**Comment by elsand** [comment]
As per discussions on Slack, option 1 seems to be the most appropiate approach here. As mentioned this will require that we aquire a separate (supplier) token that is passed to DAN to be used against FREG.

The separate token can be aquired by using the IMaskinporten service [manually](https://github.com/Altinn/altinn-apiclient-maskinporten#manual-use-of-tokenservice). This can be done something like this:

```c#
private async Task<string> GetMaskinportenAccessTokenOnBehalfOfMunicipality(string municipalityOrgNo)
{
    // _maskinporten is a IMaskinportenService, which should already be registered in the DIC
    try
    {
        string accessToken = null;
        string base64encodedJWK = await _secrets.GetSecretAsync("myBase64EncodedJwkWithPrivateKey");
        TokenResponse accesstokenResponse = await _maskinporten.GetToken(
            base64encodedJWK,
            _maskinportenSettings.Environment,
            _maskinportenSettings.ClientId,
            _maskinportenSettings.Scope,
            null,
            municipalityOrgNo); // <-- new parameter in Altinn.ApiClients.Maskinporten v7.0.0

        return accesstokenResponse.AccessToken;
    }
    catch (Exception)
    {
        // Will throw if municipalityOrgNo hasn't delegated access to the requested scope to Digdir
    }
}
```

This token can be used in the DAN client, so that DAN will use this against Skatteetaten/FREG. Calls to GetDataSet in DataProcessor.cs should then be changed to something like

```c#
var municipalityOrgNo = "964983291"; // Need to fetch the municipality organization number from somewhere
var municipalityToken = await GetMaskinportenAccessTokenOnBehalfOfMunicipality(municipalityOrgNo);
var sokerSummertSkattegrunnlag = await _danClient.GetDataSet<SummertSkattegrunnlag>("SummertSkattegrunnlag",
    instance.InstanceOwner.PersonNumber, forwardAccessToken: municipalityToken);
```
