### ISSUE TITLE
Setting validation result in ValidateData() to *FIXED* breaks validationResults.IsValid

### ISSUE THREAD

**Issue by torbjokv** [Altinn/app-lib-dotnet#112]
I'm using the functionality documented [here](https://docs.altinn.studio/nb/app/development/logic/validation/#spesifisere-at-valideringsfeil-er-fikset) to mark fields as fixed when validated together. Later on I wanted to use `validationResults.IsValid` in my validation logic, but this is not working as I expected as it gives me `false` when there are two fixed fields and otherwise everything is valid.

## What needs to be solved?
`validationResults.IsValid` should give me `true` when everything is valid and \*FIXED\* 

![image](https://user-images.githubusercontent.com/554713/145803150-7e14df96-75f6-41d1-9e43-92b26401a5b8.png)

## How do you want it solved?
An extension method `AddModelFix` on validationResults that makes sure ModelValidationState is set to Valid maybe? This would also need ValidationAppSI  to not filter away Valid results.

## Alternative solutions
My current workaround to detect if form is valid or not
```csharp
            if (validationResults
                .Any(a => a.Value.ValidationState == ModelValidationState.Invalid && 
                            !a.Value.Errors.All(a => a.ErrorMessage.StartsWith("*FIXED*"))))
                return; // the form is invalid
```

**Comment by olemartinorg** [comment]
It might be wise to hold off on this one. The solution around \*FIXED* seems sub-optimal, and we might want to find a better (read: automatic) solution for this problem in the future. App-frontend should track where each validation message came from, and remove validation messages if subsequent requests for the same validation does not produce the same error. Alternatively, we should allow triggers for validations on multiple fields to run at once.

**Comment by ivarne** [comment]
This has been fixed with new validation interfaces and the validatitonSource concept that replaces `*FIXED*`
