### ISSUE TITLE
Det må være mulig å sende varsel til personer som skal/kan signere skjema

### ISSUE THREAD

**Issue by andersrodahl** [Altinn/app-lib-dotnet#136]
## Is your feature request related to a problem? Please describe
Når utfyller av skjema skal sende et skjema til signering er det i dagens løsning ingen mulighet til å varsle konkrete personer som har signeringsrett om at de kan logge seg på og signere skjemaet.

## Describe the solution you'd like
En mulighet er å la utfyller velge blant de personene som har signeringsrett, og sende et varsel til de valgte personene.
Varsel bør kunne gjøres både via epost og sms.

## Describe alternatives you've considered
Hvis det ikke er mulig å velge i en liste kan det være en mulighet at utfyller må angi fødselsnummer for de aktuelle personene.

Avhengig av ny varslingskomponent i Plattform.

## Additional information
* https://github.com/Altinn/altinn-support-private/issues/416

## Design
Design of this is started in [Figma](https://www.figma.com/file/wnBveAG2ikUspFsQwM3GNE/Altinn-Studio-Apps?node-id=15741%3A29639)

![image](https://user-images.githubusercontent.com/13309071/161020259-2d41decb-5394-445f-b539-8aa67a4f944e.png)

**Comment by HauklandJ** [comment]
Replaced by #791
