### ISSUE TITLE
Fra signeringssteg må det være mulig å gå tilbake og endre/korrigere opplysninger før signering gjennomføres

### ISSUE THREAD

**Issue by andersrodahl** [Altinn/app-lib-dotnet#137]
## Is your feature request related to a problem? Please describe
I dagens Altinn 3 - løsning er det ikke mulig å endre på skjemaopplysninger etter at skjemaet er sendt til signering. Dette er uheldig da personen som skal signere i noen tilfeller ønsker å korrigere opplysningene før signering gjennomføres.

## Describe the solution you'd like
Etter at utfyller har sendt skjema til signering må det være mulig for "signerer" å gå tilbake og endre/korrigere opplysninger før signering gjennomføres.
En utfordring her er at PDF'en allerede er generert når man kommer til signeringssteget. Hvis det skal være mulig å endre skjemadataene må i så fall PDF'en genereres på nytt etter endringene slik at det er den nye PDF'en som signeres.

Brønnøysundregistrene ønsker at dette prioriteres.

## Describe alternatives you've considered
> A clear and concise description of any alternative solutions or features you've considered.

## Additional context
> Add any other context or screenshots about the feature request here.

Gitt at du som utfyller har lesetilgang til signeringssteget og tilgang til action/knapp for å sende tilbake til datautfylling så blir denne issuen løst av det vi nå gjør på signering.

**Comment by FinnurO** [comment]
Ses i sammenheng med BPMN gateway

**Comment by RonnyB71** [comment]
@RonnyB71 note to self: Sjekk denne opp i mot signering og kravene der, så kan den lukkes som duplikat.
