### ISSUE TITLE
Review prefill client documentation obsolete?

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/app-lib-dotnet#144]
## Description
We have a section on prefill client under Altinn API in docs.altinn.studio. 
The prefill client has not been worked on since we got a new application structure. 
Is the documentation obsolete? If so it should probably be removed for our documentation as well. 

## Screenshots
> Screenshots or links to Figma (make sure your sketch is public)

## Considerations
> Describe input (beyond tasks) on how the user story should be solved can be put here.

## Acceptance criteria
> Describe criteria here (i.e. What is allowed/not allowed (negative tesing), validations, error messages and warnings etc.)

## Specification tasks

- [ ] Development tasks are defined
- [ ] Test design / decide test need

## Development tasks
> Add tasks here

## Definition of done
Verify that this issue meets [DoD](https://confluence.brreg.no/display/T3KP/Definition+of+Done#DefinitionofDone-DoD%E2%80%93utvikling) (Only for project members) before closing.

- [ ] Documentation is updated (if relevant)
  - [ ] Technical documentation (docs.altinn.studio)
  - [ ] User documentation (altinn.github.io/docs)
- [ ] QA
- [ ] Manual test is complete (if relevant)
- [ ] Automated test is implemented (if relevant)
- [ ] All tasks in this userstory are closed (i.e. remaining tasks are moved to other user stories or marked obsolete)

**Comment by lvbachmann** [comment]
I cannot find the page this issue is referring to. Maybe it's been removed @acn-sbuad?

**Comment by acn-sbuad** [comment]
Closing due to age. Docs has hopefully been improved since issue was first created
