### ISSUE TITLE
Look into 409 responses if pdf generation has failed 

### ISSUE THREAD

**Issue by lorang92** [Altinn/app-lib-dotnet#171]
## Description
When investigating Altinn/altinn-studio#5007 it was discovered that if app-frontend tries to change data/submit after a next-call has been called and pdf generation failed we got in a state where all put/post calls from app-frontend for updating form data returns 409-conflict.  Confusing for the end-user and seems like an unwanted state for the instance.

We should look into why this happens and mitigate this issue.

## In scope
- Find root cause of issue
- Are there alternative ways to handle pdf-generation / process next?
  - One alternative is to generate the pdf successfully before we do anything else for the process

## Conclusion
> Short summary of the proposed solution.

## Tasks
- [ ] Is this issue labeled with a correct area label?
- [ ] QA has been done

**Comment by SandGrainOne** [comment]
I'm removing the pdf label as I think the label should be reserved for issues about the creation of pdf files. In this case the issue is that the pdf is missing, not the pdf content.

**Comment by ivarne** [comment]
The root cause is pretty obvious. The instance is locked ~before~ **while** generating PDF and not unlocked if PDF generation fails.

https://github.dev/Altinn/app-lib-dotnet/blob/856a4b6b81c4d3d4353579b8284b042717e9fed8/src/Altinn.App.Core/Implementation/DefaultTaskEvents.cs#L148-L162

```c#
    dataElement.Locked = true;
    _logger.LogInformation($"Locking data element {dataElement.Id} of dataType {dataType.Id}.");
    Task updateData = _dataClient.Update(instance, dataElement);

    if (generatePdf)
    {
        Type dataElementType = _appModel.GetModelType(dataType.AppLogic.ClassRef);
        Task createPdf =
            _pdfService.GenerateAndStoreReceiptPDF(instance, endEvent, dataElement, dataElementType);
        await Task.WhenAll(updateData, createPdf);
    }
    else
    {
        await updateData;
    }
```

**Comment by RonnyB71** [comment]
Closing, duplicate of https://github.com/Altinn/app-lib-dotnet/issues/504
