### ISSUE TITLE
Fields without data causes NullReferenceException in PdfOptionsMapping during PDF-generation

### ISSUE THREAD

**Issue by andsjo-svv** [Altinn/app-lib-dotnet#184]
### Description of the bug

The method GetMappingValues in PdfOptoinsMapping encounters a NullReferenceException on this line `selectedDatas.Add(jsonData.SelectToken(select).ToString());` when `jsonData.SelectToken(select)` returns `null `and `ToString()` is called on `null`.
This occurs in our application during PDF generation and seems to be related using dynamic options, the keyValuePairs, on checkboxes.

The for-loop in GetMappingValues loops through a set of fields in the data model, if one of these fields contain no data the NullReferenceException occurs.
In our case this occurs because all fields will not always have a value. We can not circumvent this by filling dummy data in relevant fields as some of these have a restriction on legal values which causes validation errors. 
This error first occured in v5 of the Altinn Nuget packages and is still present in v7.

Relevant part of JSON-datamodel:
```
  "soknad": {
    "transportorOrgnummer": "979599498",
    "soknadtype": "new",
    "nyGaranti": {
      "garantinummer": "1",
      "garantitype": "TURVOGN",
      "belop": "1000000",
      "gyldigFraDato": "2023-02-02T12:00:00+01:00",
      "loyvedekning": 0,
      "skjemaBekreft": "confirm"
    },
    "endreGaranti": null,
    "erstattGaranti": null,
    "erstattAndreGarantister": null,
    "skjemaBekreft": null,
    "loyvedekning": null
  }
```
  
Relevant part of layout JSON-file:
```
   {
	"id": "ErstattEgenGarantiCheckboxes",
	"type": "Checkboxes",
	"textResourceBindings": {
	  "description": "Velg hvilke garantier du ønsker å erstatte",
	  "title": "Erstatt garantier"
	},
	"dataModelBindings": {
	  "simpleBinding": "soknad.erstattGaranti.gammelGarantinummer"
	},
	"optionsId": "transportTillatelserErstattEgenGaranti",
	"secure": true,
	"mapping": {
	  "soknad.soknadtype": "soknadtype",
	  "soknad.erstattGaranti.garantitype": "valgtGarantitype",
	  "soknad.transportorOrgnummer": "transportOrgnummer",
	  "orgNoGarantist": "garantistOrgnummer"
	},
	"required": true
  }
```
  
`soknad.endreGaranti` is `null `here which causes the exception in `selectedDatas.Add(jsonData.SelectToken(select).ToString());`

### Steps To Reproduce

Can be reproduced on branch PDF_NullReferenceException of svv/transportloyvegarantier.
1. Start the application and open transportloyvegarantier with the user Sophie Salt representing DDG Fitness.
2. Fill in a 9 digit number in the field "Organisasjonsnummer til transportør"
3. Scroll down and click the button "Ny garanti"
4. Fill al the fields, upload a PDF file, and checkbox at the bottom
5. Click "Send inn"

Can probably be reproduced in any app by adding radio buttons that uses dynamic options in a similar way.

**Comment by olemartinorg** [comment]
Link to discussion on Slack:
- https://altinn.slack.com/archives/C02ESDT071T/p1675343538806029
