### ISSUE TITLE
Store tall i "kort svar" kaster feilmelding - Could not convert string to decimal

### ISSUE THREAD

**Issue by rvessb** [Altinn/app-lib-dotnet#197]
### Description of the bug

Dersom man taster inn veldig store tall i et inputfelt koblet til et numerisk felt i datamodellen får man "ukjent feil" i skjemaet.  
![image](https://user-images.githubusercontent.com/43333852/220924708-0e53815d-2b78-4698-9ac2-a27869783328.png)
![image](https://user-images.githubusercontent.com/43333852/220924780-3163f6eb-9d64-4e73-abde-6132d174258f.png)

Se slack-tråd: 
https://altinn.slack.com/archives/C02EVE4RU82/p1677157163157629

### Steps To Reproduce

- Opprett ett numerisk felt i datamodell
- Koble det numeriske feltet til et inputfelt i skjemaet (kort svar)
- Legg inn knapp for sidebytte og sett "validate page" på denne.
- 
- Kjør skjemaet 
- Tast inn minst 31 tall 
- Trykk gå til neste side
- Feilen skal nå ha oppstått

### Additional Information
* Backend gir ikke nok versjon til frontend for å kunne validere grensene på en Int32. Vi trenger å sende med grensene for Int i Json Schema. Vi ønsker også å få med datatypen, ikke bare grenseverdiene.
* Frontend validerer ikke skjema før lagring per i dag. Vi trenger å gjøre en validering på frontend for å fange feil av denne typen før vi prøver å lagre.

Blocked by: https://github.com/Altinn/app-frontend-react/issues/1175

**Comment by rvessb** [comment]
![Could not convert string to decimal](https://user-images.githubusercontent.com/43333852/220926939-66f2e888-1dc0-484e-a967-136abd632c7d.gif)

**Comment by olemartinorg** [comment]
Transferring this to `app-lib-dotnet`, as the error happens there. The backend seems to throw an error when attempting to cast this value upon _saving_, but we should allow for saving of values even if they're not _valid_ (validation is the next step, and is independent of saving).

**Comment by olemartinorg** [comment]
Virker til å være duplikat av #134. Lar det være opp til utviklerne som jobber mest i dette repoet å vurdere om den ene eller andre skal lukkes.

**Comment by SandGrainOne** [comment]
Jeg tror det skal være mulig å sette opp en regel som gjør at data som er identifisert som ugyldig blir ekskludert i kallet til backend, men jeg husker ikke hvordan det settes opp. Kanskje noe @nkylstad kjenner?

**Comment by olemartinorg** [comment]
Dette skal være løst nå, i forbindelse med skikkelig tallstøtte via JsonPatch-lagring i v4 av frontend. Det vil si, vi sender ikke lengre over slike store verdier til backend i det hele tatt. Se https://github.com/Altinn/app-frontend-react/issues/1749 for mer detaljer om dit vi vil rundt validering av dette.
