### ISSUE TITLE
DataElement blir ikke oppdatert ved UpdateData av filer

### ISSUE THREAD

**Issue by KristofferMagelssen** [Altinn/app-lib-dotnet#198]
### Description of the bug

Behov for metode for å oppdatere et dataelement for en auto-opprettet datatype.
For å gjøre løsningen vår mer robust ønsker vi å auto-opprette datatypene Betalingsinformasjon, Utfyllingslogg, og Godkjenningslogg. Deretter oppdatere innholdet i et gitt steg i prosessen.

Vi har forsøkt å benytte metoden UpdateData() i IData. Men når vi benytter denne metoden blir ikke metadataen for filen oppdatert. F.eks så blir data size brukt av oss og flere SBS som contentLength når man skal lese filen. Hvor da size er 304, men den skulle egentlig ha vært 1016 etter vi ersatttet filen.

Vi har også prøvd å bruke metoden Update() for å oppdatere metadataen, men det hadde ingen virkning når vi testet.

Eksempel på dataelement før vi gjorde endringen med å auto-opprette og erstatte:
`{
"id":"08dcd113-8229-490d-a76f-a714cd1d5e4e"
"instanceGuid":"52ea4031-82eb-4595-9cb8-1cac39c0abe3"
"dataType":"betalingsinformasjon"
"filename":"betalingsinformasjon.xml"
"contentType":"text/xml"
"blobStoragePath":"skd/mva-melding-innsending-etm2/52ea4031-82eb-4595-9cb8-1cac39c0abe3/data/08dcd113-8229-490d-a76f-a714cd1d5e4e"
"selfLinks":{
"platform":"https://platform.tt02.altinn.no/storage/api/v1/instances/51486373/52ea4031-82eb-4595-9cb8-1cac39c0abe3/data/08dcd113-8229-490d-a76f-a714cd1d5e4e"
}
"size":868
"locked":false
"refs":[]
"isRead":true
"created":"2023-02-06T11:41:54.7741751"
"createdBy":"158848"
"lastChanged":"2023-02-06T11:41:54.7741751"
"lastChangedBy":"158848"
}`

Eksempel på etter:
`
{
"id":"0fa141e1-338f-4667-9122-2af8121e5823"
"instanceGuid":"9920cf45-b165-4900-825c-30f7c2bc0f82"
"dataType":"betalingsinformasjon"
"filename":"betalingsinformasjon..xml"
"contentType":"application/xml"
"blobStoragePath":"skd/mva-melding-innsending-etm2/9920cf45-b165-4900-825c-30f7c2bc0f82/data/0fa141e1-338f-4667-9122-2af8121e5823"
"selfLinks":{
"platform":"https://platform.tt02.altinn.no/storage/api/v1/instances/51486373/9920cf45-b165-4900-825c-30f7c2bc0f82/data/0fa141e1-338f-4667-9122-2af8121e5823"
}
"size":304
"locked":true
"refs":[]
"isRead":true
"created":"2023-02-06T12:27:09.1305135"
"createdBy":"158848"
"lastChanged":"2023-02-06T12:27:09.1305135"
"lastChangedBy":"158848"
}
`

### Steps To Reproduce

1. Sette autoCreate til true i applicationmetadata.json
2. Satt classRef til C# klassen som tilhører datatypen
3. Laget en klasse med interface, hvor IData.UpdateData() blir kalt, deretter blir IData.Update() kalt rett etterpå.
- Eksempel: https://altinn.studio/repos/skd/mva-melding-innsending-etm2/src/branch/feature/MEMO-11178_Auto-opprett_og_erstatt_egenlagde_filer/App/logic/TaskProcessing/Steg/OpprettBetalingsinformasjon.cs
4. Når vi da går gjennom stegen i appen, og skal hente ut filen, så stemmer ikke metadataen vi leser fra instansen med det vi forventer. 

### Additional Information

label: org/skd

**Comment by KristofferMagelssen** [comment]
Gjelder
label: org/skd

**Comment by nkylstad** [comment]
@RonnyB71 This issue was registered in altinn-studio repo, transferred it to app-lib repo now.

**Comment by ElaineSvartis** [comment]
@nkylstad Hei, SKD etterlyser tilbakemelding på denne saken. Har dere noen status vi kan gi dem?

**Comment by tjololo** [comment]
Ligger hos team apps, vi har ikke tatt denne inn i noen sprint, men skal spille den inn til PO

**Comment by kristianlie** [comment]
Spørsmålet vårt er vel først og fremst om vi bruker API-et riktig. Eventuelt om det er andre metoder vi kan benytte?

**Comment by tjololo** [comment]
Første tanke når jeg ser på appen er at det er mer korrekt å benytte InsertBinaryData som siste versjon av koden deres gjør.
UpdateData burde nok egentlig hett UpdateFormData da denne er ment for å oppdatere skjemadata.
Når det er sagt så har vi nok her en mulig bug som gjør at metadata ikke blir oppdatert korrekt så jeg vil fortsette å undersøke hva som er grunnen til oppførselen dere ser.
Videre så oppdaget jeg også at UpdateBinaryData metoden tar HttpRequest som input noe som gjør det veldig vanskelig å benytte denne fra andre steder i koden enn fra en Controller, skal få opp en issue for å utvide IData med en metode som gjør oppdatering av binære vedlegg enklere.

**Comment by tjololo** [comment]
Jeg har testet test applikasjonen min som jeg klarte og gjenskape feilen med lokalt i tt02, der opplever jeg ikke samme oppførsel og metadata på instansen under data elementet blir oppdatert. Kan dere verifisere om dere opplevde dette ute i et miljø eller bare i localtest på lokal maksin @KristofferMagelssen

**Comment by KristofferMagelssen** [comment]
Var også testet ute i tt02 på skd/mva-melding-innsending-etm2 appen. 
Var da vi først oppdaget problemet ettersom et regnskapsystem som drev og testet rapporterte at de begynte å få filer uten alt innoldet. Det var når vi brukte UpdateData at den ikke stemte, vi har ikke noe problemer med InsertBinaryData.

> Videre så oppdaget jeg også at UpdateBinaryData metoden tar HttpRequest som input noe som gjør det veldig vanskelig å benytte denne fra andre steder i koden enn fra en Controller, skal få opp en issue for å utvide IData med en metode som gjør oppdatering av binære vedlegg enklere.

Ja, det var en av grunnene til vi gikk for UpdateData, men vi så også at den var mer rettet mot skjema.

**Comment by tjololo** [comment]
I min test app så testet jeg å oppdatere en dataType på Task end via UpdateData for å undersøke om size ble oppdatert. Den ble ikke oppdatert i localtest, men ble oppdatert i tt02.
Hvis InsertBinaryData fungerer for deres usecase så oppretter jeg en issue på forbedre IData.UpdateBinaryData også lukker jeg denne hvis det er greit for dere? Mulig storage har fått oppdatering siden dere testet sist med UpdateData også.

**Comment by KristofferMagelssen** [comment]
Det høres bra ut

**Comment by tjololo** [comment]
Workaround fungerer, videre arbeid følges opp i ##228 
Lukker issuen etter avtale med innmelder
