### ISSUE TITLE
Duplicate dataelements du to raceconditions when autoCreate is set to true

### ISSUE THREAD

**Issue by tjololo** [Altinn/app-lib-dotnet#204]
### Description of the bug

It is possible to end up with multiple dataelements in an instance when instantiating and uploading a dataelemnt via the api when autoCreate is set to true.

### Steps To Reproduce

1. Create an application with a autoCreate=true
2. Instantiate a new instance and create a dataelement in a loop
3. Some instances could end up with multiple dataelements leaving it in a erroneous state

### Additional Information

Workaround: disable autoCreate

**Comment by tjololo** [comment]
Seems like the root of this problem is eventual consistency in storage. We need to handle this in the correct place

**Comment by RonnyB71** [comment]
Backend is ending up with validating errors against the wrong dataelement (empty) while the user is on another. Happened recently at Finanstilsynet causing a manul fix in Storage by the Core team.

**Comment by tjololo** [comment]
After migration of database in core we cannot reproduce this. Closing as not reproducable
