### ISSUE TITLE
Support new env variables in app-lib 7.7.0+ in deploy pipelines 

### ISSUE THREAD

**Issue by tjololo** [Altinn/app-lib-dotnet#213]
### Description

Version 7.7.0 introduces new environment variables. These needs to be incorporated into the deploy pipeline

### Additional Information

The new variables need to be in addition to the existing ones to have backwards compatability.

**Comment by RonnyB71** [comment]
This is done as a quick fix brute forcing some space for additional variables. This issue however takes into account a more permanent solution where the environment variables are kept in a separate file to avoid a character limit in the pipeline step.

**Comment by tjololo** [comment]
Updated deployscripts in all environments
