### ISSUE TITLE
Removal of hidden fields creates new data element

### ISSUE THREAD

**Issue by nkylstad** [Altinn/app-lib-dotnet#215]
### Description of the bug

When automatically removing hidden elements `OnEndProcessTask`, the `InsertFormData` method is used rather than the `UpdateFormData` method, and this causes a new data element with the updated data to be created, instead of updating the existing data element.
The instance is then left with 2 data elements for the same data (one with hidden data fields and one without).

### Steps To Reproduce

1. Go to an app with dynamic layout expressions hiding some fields
2. Fill out the form, make sure that there is some data in one of the fields that is subsequently hidden by the logic, so that there is data to remove `OnEndProcessTask`.
3. Before submitting, see that there is only 1 data element for the instance.
4. Submit the form
5. See that there are now 3 data elements - the original, a copy without the hidden fields, and the PDF.

**Comment by tjololo** [comment]
Closing this as it was resolved in https://github.com/Altinn/app-lib-dotnet/pull/216 and released in [v7.7.0](https://github.com/Altinn/app-lib-dotnet/releases/tag/v7.7.0)
