### ISSUE TITLE
Log level debug and information missing from AI

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/app-lib-dotnet#223]
## Description 

Default app based on template only logges messages of severity 3 and higher to application insights (warning, error, critical). 

## Fix
To ensure that log level information and upwards is logged to application insights the following code was added to program.cs 

```cs

void ConfigureLogging(ILoggingBuilder logging)
{   
    string applicationInsightsKey = Environment.GetEnvironmentVariable("ApplicationInsights__InstrumentationKey");

    if (!string.IsNullOrEmpty(applicationInsightsKey))
    {
        logging.AddApplicationInsights(
                  configureTelemetryConfiguration: (config) => config.ConnectionString = string.Format("InstrumentationKey={0}", applicationInsightsKey),
                  configureApplicationInsightsLoggerOptions: (options) => { });

    // To filter out higher log leves change LogLevel.Information to desired enum value. Will include this leven and higher
     logging.AddFilter<Microsoft.Extensions.Logging.ApplicationInsights.ApplicationInsightsLoggerProvider>(string.Empty, LogLevel.Information);      
    }
}
```

Call this function as the final step before `builder.Build()` i.e. 

```cs
WebApplicationBuilder builder = WebApplication.CreateBuilder(args);

ConfigureServices(builder.Services, builder.Configuration);

ConfigureWebHostBuilder(builder.WebHost);
ConfigureLogging(builder.Logging);

WebApplication app = builder.Build();

Configure();

app.Run();

```

**Comment by acn-sbuad** [comment]
What are next steps? hand over to team apps to implement support for it? Document for app owners to be able to add to their apps themselves?

**Comment by SandGrainOne** [comment]
@RonnyB71 Is this something your team would consider adding to the app template?

**Comment by RonnyB71** [comment]
Today we have the following method for adding ApplicationInsights:
```csharp
private static void AddApplicationInsights(IServiceCollection services, IConfiguration config, IWebHostEnvironment env)
        {
            string applicationInsightsKey = env.IsDevelopment() ?
                         config["ApplicationInsights:InstrumentationKey"]
                         : Environment.GetEnvironmentVariable("ApplicationInsights__InstrumentationKey");

            if (!string.IsNullOrEmpty(applicationInsightsKey))
            {
                services.AddApplicationInsightsTelemetry(applicationInsightsKey);
                services.AddApplicationInsightsTelemetryProcessor<IdentityTelemetryFilter>();
                services.AddApplicationInsightsTelemetryProcessor<HealthTelemetryFilter>();
                services.AddSingleton<ITelemetryInitializer, CustomTelemetryInitializer>();
            }
        }
```
Your change seems like something we should implement here?

**Comment by acn-sbuad** [comment]
Main difference here is adding AI to the logger vs adding a service to forward telemetry (not nessesarily log data). Check out docs that highlights some of the differences: https://learn.microsoft.com/en-us/azure/azure-monitor/app/ilogger?tabs=dotnet6

In the platform components we use both to ensure we capture both data related to the incomming requests as well as general logs from the applications.

**Comment by RonnyB71** [comment]
> @RonnyB71 Is this something your team would consider adding to the app template?

Yes, this should go into the template as default but still with the current log levels set as default.

**Comment by ivarne** [comment]
Isn't these settings usually put in `appsettings.json` under `Logging.ApplicationInsights.LogLevel`?

```json
{
  "Logging": {
    "LogLevel": { // No provider, LogLevel applies to all the enabled providers.
      "Default": "Error",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Warning"
    },
    "ApplicationInsights": {
      "LogLevel": {
        "Default": "Information"
      }
    }
  }
}
```

ApplicationInsights default configuration is to ignore anything below `Warning`, which seems to be the issue here.

**Comment by tjololo** [comment]
Tested this with the settings @ivarne mentioned in appsettings.json.
Applications logs debug, information, warning and error to AI and I'm able to view the logmessage connected to the trace that generated them.
I think this issue can be closed as we already support sending logs of any level to applicaiton insights
