### ISSUE TITLE
Unusable HttpClient in app-lib

### ISSUE THREAD

**Issue by DanRJ** [Altinn/app-lib-dotnet#235]
### Description of the bug

The following HttpClient is unusable after Platform.Register updated their API, with 2 custom headers, one for norwegian national number and one for last name.

The HttpClient implements the old way of fetching a person.
https://github.com/Altinn/app-lib-dotnet/blob/main/src/Altinn.App.Core/Infrastructure/Clients/Register/RegisterDSFClient.cs

### Steps To Reproduce

The code only fails.

**Comment by RonnyB71** [comment]
@DanRJ What change in the Platform.Register source are you refering to?

**Comment by DanRJ** [comment]
On this line in the HttpClient:
https://github.com/Altinn/app-lib-dotnet/blob/main/src/Altinn.App.Core/Infrastructure/Clients/Register/RegisterDSFClient.cs#L64

The endpoint in Platform.Register no longer accepts national identity numbers in the URI, it only accepts 2 custom headers, one for nin and one for lastname.

This is the updated endpoint for Platform.Register:
https://github.com/Altinn/altinn-register/blob/main/src/Controllers/PersonsController.cs#L53

**Comment by tjololo** [comment]
I think we should mark the RegisterDSFClient and IDSF as obsolete as long as there are no way of querying register that way.
There is a new client [IPersonRetriever](https://github.com/Altinn/app-lib-dotnet/blob/main/src/Altinn.App.Core/Interface/IPersonRetriever.cs) that uses the new header values with SSN and Lastname to get a Person from Platform.Register

**Comment by ivarne** [comment]
These interfaces are obsolete in v8
