### ISSUE TITLE
Add support for getting the requested URL from a codelist for documentation

### ISSUE THREAD

**Issue by RonnyB71** [Altinn/app-lib-dotnet#256]
### Description

In order to document the source of a used codelist we need to expose the requested url to the application so we can store and document what the url was when it was used.

### Additional Information
Clarifying the usage - it's not required with the url it self, but the parameters used when getting the codelist. The url might often not be generated due to caching. But the parameters will always be passed and can be returned for documentation purposes.

### Solution
When backend responds with the options, the metadata/parameters used against the underlying api should be included in the response as a urlencoded header -> X-Altinn-DownstreamParameters

Frontend writes these metadata from the header to a configured field. Add the posibility to configure the datamodel binding to where in the datamodel the values should be stored.

Should be reimplemented with Tanstack Query ref. https://github.com/Altinn/app-frontend-react/issues/1294

### Acceptance Criterias

- [ ] The parameters that was used should be exposed in the options api allowing it the be read by application developers
- [ ] All places where options are used should have the option to configure where the parameteres should be stored.

**Comment by RonnyB71** [comment]
Nuget v7.14.0-preview.1 created with backend changes.

**Comment by lassopicasso** [comment]
Tested for v3 and v4, both work nicely! Well done @Magnusrm ! 🚀
