### ISSUE TITLE
Add `Source` to `ValidationIssue`

### ISSUE THREAD

**Issue by bjosttveit** [Altinn/app-lib-dotnet#287]
### Description

Add sources for the different kind of validations so that frontend can filter out the types of validations it does on its own to avoid duplicate validations with different text.

**Comment by tjololo** [comment]
Before upgrading to this version of app-lib:


![Image](https://github.com/Altinn/app-lib-dotnet/assets/1145298/898dc4a2-5610-4b3c-b12f-752de837cd25)

After upgrading to this version of app-lib:


![Image](https://github.com/Altinn/app-lib-dotnet/assets/1145298/c74bf3da-1db2-45da-81ec-b07495a1d907)
