### ISSUE TITLE
ApplicationMetadata - Logo declaration is removed when generating model in Altinn.Studio

### ISSUE THREAD

**Issue by ghost** [Altinn/app-lib-dotnet#312]
### Description of the bug

The object `logo` is deleted from `applicationMetadata.json` when you generate model in altinn.studio.

### Steps To Reproduce

1. Add ` "logo": {
   "source": "org",
   "size": "medium"
 }` to `applicationMetadata.json`
2. Push the code
3. Go to altinn.studio
4. Generate model

**Comment by ivarne** [comment]
Fixed in https://github.com/Altinn/altinn-studio/issues/11357
