### ISSUE TITLE
Expose the app-lib-dotnet version to app-frontend in applicationmetadata

### ISSUE THREAD

**Issue by olemartinorg** [Altinn/app-lib-dotnet#315]
### Description

We have a need for requiring a minimum backend version in app-frontend, so the backend should expose its current version to us in some way.

### Additional Information

- https://github.com/Altinn/app-frontend-react/issues/1496

**Comment by ivarne** [comment]
Fixed by https://github.com/Altinn/app-lib-dotnet/pull/333
