### ISSUE TITLE
Make v7-v8 update scripts introduce Layout sets for all apps that don't have them

### ISSUE THREAD

**Issue by ivarne** [Altinn/app-lib-dotnet#335]
### Description

Frontend wants to simplify by only having one concept.

This means that all apps need to be updated to use layoutsets.

See:
* https://github.com/Altinn/app-frontend-react/issues/1485

**Comment by olemartinorg** [comment]
Implemented in:
- https://github.com/Altinn/altinn-studio-cli/issues/10
