### ISSUE TITLE
Add source generator for adding row id on data models compile time

### ISSUE THREAD

**Issue by ivarne** [Altinn/app-lib-dotnet#435]
### Prerequisites:
- Data model classes has the `partial` modifier (at least those that are part of a list)

### Decisions
- Decide name for the row id
- Automatically find data model classes that are used in a `List<>` property, or require those classes to use a special attribute (eg. `[AddAtinnRowId]`)

### Tasks
- [ ] Add and initialise source generator project
- [ ] Add generator functionality to add the relevant partial classes

### Sample class
```c#
// Current model.cs
...
[AddAltinnRowId] //(Not sure if we want to require this)
public partial class ListItem
{
    public string? Name { get; set; }

    public int? Age { get; set; }
}

// model.g.cs (generated file)
public partial class ListItem
{
    [XmlAttribute("altinnRowId")]
    [JsonPropertyName("altinnRowId")]
    public Guid? AltinnRowId { get; set; } = Guid.NewGuid();
}
```

**Comment by RonnyB71** [comment]
Won't use this solution, closing the issue.
