### ISSUE TITLE
Behov for standardiserte sentinel verdier i kodelister

### ISSUE THREAD

**Issue by RonnyB71** [Altinn/app-lib-dotnet#443]
### Description

Flere kodelister er "rene kodelister" dvs. de har ikke verdier som "Ikke relevant", "Ikke oppgitt", "Ikke valgt" etc. I mange tilfeller er det ønskelig å presentere denne type verdier i grensesnittet til sluttbruker f. eks. i et rullegardin felt sammen med de reelle verdiene som f. eks. kan være en liste over kommuner eller en hvilken som helst annen kodeliste.

Samtidig kan det være et behov for å holde de underliggende kodelistene helt rene, og ikke blande inn denne type verdier direkte i listene selv om dette også er en løsning. Og i noen lister er dette faktisk gjort.

Uavhengig av løsning er behovet der for å kunne eksponere denne type verdier og "skjøte" disse på den aktuelle kodelisten uten å måtte gå inn å lage en custom kodeliste hvor dette kodes i C# (som er dagens løsning på dette).

### Additional Information

Alternative løsningsforslag:
1) Konfigureres sammen med kodelisten når denne legges til i Program.cs - dvs. man konfigurerer hvilke sentinel verdier som skal legges på.
2) Man spesifisererer en annen standard kodeliste for sentinel verdier og det som presenteres ut fra backend blir da en sammenslått liste

I begge disse forslagene vil det potensielt være en utfordring med metadatadokumentasjon av hvilke kodelister som ble brukt og hvilke verdier som var tilgjengelig på det tidspunktet brukeren fylte ut skjema.

### Acceptance Criterias
- [ ] Man skal kunne kombinere to kodelister og resultere det som et samlet resultat
- [ ] Det skal ikke være noen duplikate verdier i det sammenslåtte resultatet
- [ ] Ved evt. duplikat skal det returneres en feilmelding til frontend
- [ ] Det må være mulig å samle sentinel verdiene nederst i den totale listen, evt. gjøre det konfigurerbart topp/bunn evt. samlet sortering
- [ ] Sortering må kunne gjøres på enten: visningsverdi, shortname eller code (evt. en custom implementering)
- [ ] Altinn-DownstreamParameters må reflektere parametre for begge kodelister

**Comment by StianVestli** [comment]
`List<string> knownKeys = new () { "id", "variant", "date", "language", "level", "parentCode" };`
    `    foreach (var keyValuePair in mergedKeyValuePairs)
        {
            if (!knownKeys.Contains(keyValuePair.Key))
            {
                appOptions.Parameters.TryAdd(keyValuePair.Key, keyValuePair.Value);
            }
        }
`

Vil ikke koden over legge inn eventuelle andre konfig verdier som brukte parametere som feks sentinel verdier? slik at vi kan hente dette ut i koden? Eller har jeg tolka denne feil kanskej?

**Comment by rvessb** [comment]
Etter å ha drodlet rundt dette med @StianVestli heller vi sterkt mot løsning 2.  Vi oppretter en egen kodeliste felles for alle A3-tjenester som kun holder på sentinelverdier, riktige verdier fra denne lista gjøres da med "codeSelect". 
Dette betinger altså at man kan kombinere 2 klass-kall der begge kallene støtter dagens funksjonaliet. 
Etter sammenslåing av resultatet fra de to kallene må det kjøres en dublettsjekk på "key". Dersom dublett oppdages bør hele resultatet forkastes og kun returnere noe slik som feks  "Klass returnerte dublett".

**Comment by rvessb** [comment]
@RonnyB71 Jeg har opprette egen kodeliste i Klass for sentinelverdier som kan brukes for å teste "kombinasjon" av kodelister. https://www.ssb.no/klass/klassifikasjoner/707.

Eksempel på kall: https://data.ssb.no/api/klass/v1/classifications/707/codesAt?date=2024-02-03&language=nb&selectCodes=0574.ZZ6.*

**Comment by ivarne** [comment]
Foreslått løsning: JoinedCodeListProvider

En ny kodeliste registrering som tar inn to (eller flere) andre options id, og lager en registrerer en ny options id med en ny id

```C#
services.AddSSBClassificationCodelistProvider("næring", Classification.IndustryGrouping);
services.AddSSBClassificationCodelistProvider("sentinel", Classification.Sentinel);
services.AddJoinedOptionsProvider("næring-sentinel", "næring", "sentinel");
```

I appen kan man da bruke kodelisten `"optionId": "næring-sentinel"` som inneholder først alle elementene fra `"næring"` og deretter verdiene fra `"sentinel"` listen. Denne vil også støtte options fra json filer. Sortering kan da potensielt gjøres på hver enkelt del av listen (om de tilbyr config for dette).

Utvidelser (mulig de blir lagt inn som issues eller gjort som del av førsteutkast)
* Støtte `AddJoinedInstanceOptionsProvider`, som kan refere til både `instanceOptions` og `appOptions`
* Støtte mulighet for å konfigurere server side sortering av hele den kombinerte listen.

**Comment by bjorntore** [comment]
Testet OK.
