### ISSUE TITLE
IUserAction does not support PATCH and incremental validation.

### ISSUE THREAD

**Issue by ivarne** [Altinn/app-lib-dotnet#446]
### Incremental validation

IUserAction can return new versions of data models so that the backend can modify data when executing the action. To make that work with incremental validation, we need to know both the previous and the new state of the data model. It is inefficient to fetch the data both in the action and then again in the controller to be able to see the previous data for validation. Consider adding a new interface `IDataUserAction` that first fetches the model, just as we use for ProcessDataWrite

### Multiple instances of the same data type
As the return dictionary of `IUserAction` is indexed on dataTypeId, instead of dataElementId, it only supports 1 instance of each data type.

**Comment by tjololo** [comment]
As the changes made to the datamodel in `IUserAction` is entirely handled by the developer also writing the validation logic could the incremental validation be something that is opt-in? We could either extend the response with a list of elementIds that should be validated where we force the developer to provide the original version of the data?

**Comment by ivarne** [comment]
I'm not sure. Actions are likely a to be executed way less than PATCH, so I would not expect the double fetch to make a difference in app performance.

My first thought was that the interface needs adjusting, but now that I have written the compatibility code, I suspect the simple interface is kind of enough compensation.

A new/changed interface would in my opinion need a way to register the models it needs, and get them as parameters, not fetch them manually.

**Comment by ivarne** [comment]
fixed by https://github.com/Altinn/app-lib-dotnet/pull/441
