### ISSUE TITLE
Signatures are not deleted when process is reversed

### ISSUE THREAD

**Issue by ivarne** [Altinn/app-lib-dotnet#460]
## Description of the bug

When an app has two signature steps and the second one is refused, the old first signature object stays and the result is 3 instead of 2 signature objects, one of which is invalid

## Discussion
Discussion and proposed new feature is documented in #617

**Comment by tjololo** [comment]
Implementing this feature request in Storage will resolve this issue: https://github.com/Altinn/altinn-storage/issues/351

**Comment by bjorntore** [comment]
Am I reading the code correctly: We will delete any data element where a reference exists with RelationType="GeneratedFrom" and ValueType="Task" when the process task it was connected to is "ended"? See https://github.com/Altinn/app-lib-dotnet/blob/main/src/Altinn.App.Core/Internal/Process/ProcessTasks/Common/ProcessTaskFinalizer.cs#L60.

Is that not a bit aggressive?

Maybe we instead should configure on the data type if it should be auto deleted when the process step is ended/abandoned?

If we want to always delete data elements with such a relation if "reject" is called on a task, maybe we should stick it in AbandonTaskEventHandler?

For Signature specifically, it could also have been solved by implementing this in the SigningProcessTask.Abandon method.

**Comment by ivarne** [comment]
> For Signature specifically, it could also have been solved by implementing this in the SigningProcessTask.Abandon method.

No, that will not solve the issue when the signature task is not the last task in the process, and someone wants to go back past a previous signature task to change something.

**Comment by bjorntore** [comment]
> > For Signature specifically, it could also have been solved by implementing this in the SigningProcessTask.Abandon method.
> 
> No, that will not solve the issue when the signature task is not the last task in the process, and someone wants to go back past a previous signature task to change something.

I should have written "maybe". :P

**Comment by ivarne** [comment]
I have previously asked the exact same question

**Comment by danielskovli** [comment]
This has been implemented in https://github.com/Altinn/app-lib-dotnet/pull/617 and merged to main.
