### ISSUE TITLE
"list.Count-1" not working as index for CreateValidationIssue

### ISSUE THREAD

**Issue by CelineTrammi** [Altinn/app-lib-dotnet#506]
### Description of the bug

I wanted to validate a field in a repeating group by placing the validation message at the last element. However, using this:
```Csharp
var norskeEiere = model.Oppgave.rapporteringsenhet.eierforhold.norskeEiere;
CreateValidationIssue(c => c.Oppgave.rapporteringsenhet.eierforhold.norskeEiere[norskeEiere.Count-1].eierandel, errMsg);
```
results in an index error. 
Workaround:
```
var norskeEiere = model.Oppgave.rapporteringsenhet.eierforhold.norskeEiere
int i = norskeEiere.Count - 1;
CreateValidationIssue(c => c.Oppgave.rapporteringsenhet.eierforhold.norskeEiere[i].eierandel, errMsg);
```

### Steps To Reproduce

1. Create a repeating group component
2. Create a FormDataValidator, or GenericFormValidator
3. Validate on the last element in a group, using `group.Count`
4. Trigger the validation code from the App

**Comment by ivarne** [comment]
Suggested failing test for test/Altinn.App.Core.Tests/Helpers/LinqExpressionHelpersTests.cs
```C#
    [Fact]
    public void GetJsonPath_AritmeticExpression()
    {
        var list = new List<string>
        {
            "one",
            "two"
        };
        var propertyName = LinqExpressionHelpers.GetJsonPath<MyModel, int?>(m => m.Children![list.Count - 1].Age);
        propertyName.Should().Be("Children[1].age");
    }
```

See: https://github.com/Altinn/app-lib-dotnet/pull/424 for previous solution to a similar issue.
