### ISSUE TITLE
PATCH: Saving a space and removing it causes 409 crash

### ISSUE THREAD

**Issue by olemartinorg** [Altinn/app-lib-dotnet#517]
### Description of the bug

Typing into a string field, removing the value, adding a space, removing that space (all while waiting for saving in between each step) seems to crash with a 409.

### Steps To Reproduce

https://github.com/Altinn/app-frontend-react/assets/700139/3556b56c-90be-4907-a986-2a28fbd4aa65

**Comment by olemartinorg** [comment]
I've done a bit of research here, and this seems to be a backend issue. Given this data model (pasting in a partial model here):

```xml
  <NyttNavn-grp-9313 gruppeid="9313">
    <NyttNavn-grp-9314 gruppeid="9314">
      <PersonEtternavnNytt-datadef-34757 orid="34757">  </PersonEtternavnNytt-datadef-34757>
      <PersonFornavnNytt-datadef-34758 orid="34758">hei</PersonFornavnNytt-datadef-34758>
    </NyttNavn-grp-9314>
  </NyttNavn-grp-9313>
```

(Notice that the last name is two spaces here)

I get the following model when fetching it from the backend as XML:

```json
{
  "NyttNavn-grp-9313": {
    "gruppeid": 9313,
    "NyttNavn-grp-9314": {
      "gruppeid": 9314,
      "PersonEtternavnNytt-datadef-34757": {
        "orid": 34757,
        "value": null
      },
      "PersonFornavnNytt-datadef-34758": {
        "orid": 34758,
        "value": "hei"
      },
      "PersonMellomnavnNytt-datadef-34759": null,
      "PersonBekrefterNyttNavn": null
    }
  }
}
```

Those two spaces suddenly turned into `null`! :scream: The very strange part of this is that it's not happening for some of the other string-typed input fields in the same data model. I think this might be something deeply rooted in the XML->JSON->XML conversion pipelines.

Moving this issue to `app-lib-dotnet` for further investigation there. The app we've tested this in is `ttd/frontend-test`, and this form page is one of the first ones you'll see when you start a new instance in that app.

**Comment by ivarne** [comment]
@olemartinorg do you have a simple way to remake the patch requests that causes this?

**Comment by olemartinorg** [comment]
Yup, the simplest way is probably just to load up the `ttd/frontend-test` app and do the same thing as in the video (type 'a', remove it, type a space, remove that, etc) in the same field.

**Comment by olemartinorg** [comment]
This might be relevant:
- https://altinn.slack.com/archives/C02EJ9HKQA3/p1711007303959429?thread_ts=1710493123.111109&cid=C02EJ9HKQA3

The relevant field in the data model also has the `XsdText()` annotation on it, if I recall correctly. From the thread:

> xsdText gjør slik at c# verdien i klassen ikke blir satt som nullable

**Comment by kentare** [comment]
> This might be relevant:
> 
> * https://altinn.slack.com/archives/C02EJ9HKQA3/p1711007303959429?thread_ts=1710493123.111109&cid=C02EJ9HKQA3
> 
> The relevant field in the data model also has the `XsdText()` annotation on it, if I recall correctly. From the thread:
> 
> > xsdText gjør slik at c# verdien i klassen ikke blir satt som nullable

I can add two commits that highlights that when I remove `"@xsdText": true` and then generate the models from studio solves the issue specified in the slack thread.  

Commit that deletes `"@xsdText": true` from schema.json: https://altinn.studio/repos/brg/test-aarsregnskap-ux/commit/6608d4ec72b2f06b76e04b2eec23ddcef6615b0a 

The commit that generates the new classes from studio (example of decimal is at line 284): https://altinn.studio/repos/brg/test-aarsregnskap-ux/commit/74ad5c79ea3b33dc9e727caccc33d2a7d6ca783c

**Comment by bjosttveit** [comment]
Tested frontend-test on 8.1.1, no longer crashes 👍
