### ISSUE TITLE
Signering av valgfrie dataTypes

### ISSUE THREAD

**Issue by veronikaandersen** [Altinn/app-lib-dotnet#595]
### Description

Vi har behov for å signere dataelementer, dersom de er med. Altså valgfrie dataTypes.

Når man setter opp signering, definerer man hvilke dataTypes som skal signeres. Dersom dataTypes i denne listen er valgfrie - eks de er konfigurert med minCount=0, får man feil pga manglende dataelement for signering.
Signeringen tar tilsynelatende ikke hensyn til konfigurasjonen av dataTypes i applicationmetadata.json.

Eksempel: Valgfri dataType
![image](https://github.com/Altinn/app-lib-dotnet/assets/13414928/b6c03b3d-2807-4631-8c62-4995e0d3f3da)

Signering task
![image](https://github.com/Altinn/app-lib-dotnet/assets/13414928/9f88f1c9-1572-481c-a1e2-2d772b6c8267)

Process next med signering - uten dataelement av typen IG
![image](https://github.com/Altinn/app-lib-dotnet/assets/13414928/31728dc5-09c3-4266-a315-6e429800d5b7)

Process next med signering - med dataelement av typen IG på instansen
![image](https://github.com/Altinn/app-lib-dotnet/assets/13414928/a8d87a7f-b1b4-4a85-abd5-e6f41a4e9215)

**Comment by HauklandJ** [comment]
Reprodusert.

**Comment by bjorntore** [comment]
Test: Får ikke feilmelding lenger. 👍Det ble generert en signature.json med tom dataElementSignatures array.
