### ISSUE TITLE
Navigation between Tasks via buttons not possible(?) in v4

### ISSUE THREAD

**Issue by violaguttorm** [Altinn/app-lib-dotnet#596]
### Description of the bug

Hello! 

In v3 we have used the following code for navigating back to a task, but it is not valid any more in v4, due to `"mode": "go-to-task"` and `"taskId"` no longer being valid for a button.  
```
      {
        "id": "back",
        "type": "Button",
        "mode": "go-to-task",
        "taskId": "TaskUtfylling",
        "textResourceBindings": {
          "title": "navigation.change"
        }
        ...
      },
      {
        "id": "submit",
        "type": "Button",
        "mode": "go-to-task",
        "taskId": "BREnd",
        "textResourceBindings": {
          "title": "navigation.confirm"
        }
        ...
      }
```

I tried using `NavigationButtons`, but they simply didn't show up (possibly due to this being the only layout in the given View). 

I need to go back to a previous Task somehow. 

### Steps To Reproduce

1. Use the buttons linked over.
2. Use at least two tasks.
3. Observe that it doesn't work.

**Comment by bjosttveit** [comment]
Closing this, since as mentioned in [slack](https://altinn.slack.com/archives/C02EJ9HKQA3/p1713190155689459?thread_ts=1713180907.417399&cid=C02EJ9HKQA3), the go-to-task feature was removed in v4 in favor of process actions, and this is therefore not considered a bug. Did you manage to get the "reject" action working?

**Comment by violaguttorm** [comment]
I actually missed that reply somehow, so I haven't tried yet. I will try and ask for help if it doesn't work. The case can be closed. :)
