### ISSUE TITLE
PDF from HTML

### ISSUE THREAD

**Issue by RonnyB71** [Altinn/app-lib-dotnet#63]
## Description

This epic is part of the roadmap issue https://github.com/Altinn/altinn-roadmap/issues/38 which is rewrite of today's PDF generator.

The architecture is discussed here https://github.com/Altinn/altinn-pdf/issues/16, but in short it's based on the app calling a PDF microservice providing it with a url in the app. The PDF microservice calls back to the app using the provided url, reads the generated HTML and converts to PDF which is returned to the app.

## Primary goal
* Out-of-the-box generation of a PDF that is visually presentable and accessible without the need to configure anything

## In scope
* One PDF per data model will be generated (as today)
* A default PDF generation should "just work" out of the box using an autogenerated summary page based on the layout of the data process step
  * The page needs to be printer friendly
  * Dynamics rules must be evaluated as part of the PDF generation
  * Current exclude from PDF should still work and should be evaluated after any dynamic rules
  * The PDF should have a first-page/header with information from the instance (id, timestamp, name of app, name of service owner, name of user, list of attachments, contact information to the service owner) and any other information relevant to the user.
  * The PDF should adhere to Elmers requirements for a receipt ref. https://brukskvalitet.brreg.no/elmer3/#Innsending
* Override the default generated summary page by either
  * Specify a summary page with a custom layout
* Masking of sensitive data should be supported by the components and respected by the PDF generation
* It should be possible to disable PDF generation
* Override the default generated summary page by either
  * Specify a summary page with a custom layout

### Other Requirements
- [ ] Long response times while generating PDFs needs to be handled with regards to the user
- [ ] Robust handling of services being slow/down eg. if external services are used as dynamic options

### Out of scope
* Override the default generated summary page by either
  * Specify a summary page with a custom layout
  * Use the Confirmation process step with a custom layout
* PDF generation in the app should be implemented as a BPMN Service task visible in the BPMN process
  * Navigation back in the process (after the PDF has been generated) should be supported, ie. a new PDF should be generated and presumably the existing deleted
* Asynchronous PDF generation - while this probably is the way we would like to go at some point - it introduces some big changes on the platform side
  * Ques would need to be introduced as part of the solution
  * The PDF service would need to be able to authenticate on behalf of it-self, and not the user when calling the app
  * The app needs to be able to get user data authenticated as the app and not the user. 
* Multiple data models within the same PDF
  * Frontend can only render data from one model at a time
* Hosting PDF service using Azure Container Apps
* Multiple PDF's generated for different recipients.
* Watermark on PDF
* Ability to override the default PDF generation providing a url to "anything" within the app
* Ability to anywhere in the process view the the summary page with data filled in so far
* Print CSS available for application developers

## Additional Information
* Issues implemented by the platform team: https://github.com/orgs/Altinn/projects/27/views/1
* Branch containing PDF Service Client: https://github.com/Altinn/app-lib-dotnet/pull/12

###  Authentication
* The first version of PDF generation will be done synchronously using the user token ie. the app needs to pick up the token and pass it on to the PDF service. 
  * Should the PDF service use the user token at all or operate on behalf of the app or org?
  * Token refresh logic in case the user token is about to expire needs to be considered
  * Are there cases where the user don't have access to the data?
  * A PDF based on multiple process steps/data types will potentially challenge the fact that we now require the user to have access to everything that should go in the PDF

### Misc
* Synchronous generation of the PDF
* The PDF microservice will be running in app owner's cluster
* We should have good/complete Localtest support
 
## Concepts
* Confirmation-on-screen (aka bekreftelse på skjerm) does not equal receipt! The PDF is the users receipt, the confirmation-on-screen is just a confirmation that we have received the data. While it might show some of the same information as is in the receipt PDF and even a link to the PDF, it's not the receipt - that's the PDF.

### Synchronous process with Confirm step
![synchronous_flow](https://user-images.githubusercontent.com/5430430/199018875-f419a971-ed03-4d10-bb62-670ba00e1a3e.svg)
Note that the _Form submission confirmed_ step now is a part of the process. Previously this was a implicit part of the _Confirm_ step.

### Synchronous process without Confirm step, summary as page
![synchronous_flow_withoutconfirmstep](https://user-images.githubusercontent.com/5430430/199032993-df2b24a6-131d-4334-9e25-9948a0d76396.svg)

**Comment by TheTechArch** [comment]
When are PDFs generated?

The transition from data to confirmation or when you are confirming? (if PDF should contain "receipt" info about when it was confirmed)

If generated when leaving confirmation. Should the app also provide and endpoint to download PDF when in confirmation. That could trigger PDF generation and return the streamed PDF

**Comment by FinnurO** [comment]
https://github.com/Altinn/app-frontend-react/issues/258

**Comment by olemartinorg** [comment]
Jeg og @RonnyB71 diskuterte videre om denne nå, og gjorde oss noen notater om mulige løsninger. Etter et møte hvor det ble diskutert mye rundt prosess (f.eks. tilpassing av confirmation-steget med layout, tilpassing av receipt/bekreftelse-på-skjerm-steget med layout), og hvordan PDF-generering passer inn i prosessmotoren, skulle vi gjøre klar en oppsummering. Vi diskuterte ulike løsninger:

1. PDF servicen laster frontend etter hvert prosess-steg (før prosessen flyttes videre). Backend slår sammen sidene fra hvert steg til en større PDF til slutt (eventuelt får man en PDF for hvert steg, som diskutert tidligere).
    * Fordeler: Man kan tilpasse layout for alle steg, man får med alt dette i PDF, og man trenger ikke å endre stort på app-frontend.
    * Ulemper: Går potensielt veldig tregt å bytte mellom prosess-steg (vi må vente på PDF). Backend må potensielt kunne slå sammen PDF-sider til en stor PDF og ta stilling til rettigheter i prosess-steg underveis.
    * Hvem bærer ulempene: Brukerne (som må vente).
2. Samme som nr 1, men frontend tar en større del av kompleksiteten og skrives om til å støtte en PDF-modus hvor data og layout for flere prosess-steg lastes på en gang og vises sammen i en total-oppsummering.
    * Fordeler: Man kan generere en PDF til slutt. Potensielt enklere å gjøre asynkron dersom PDF ikke må lages på det tidspunktet man står på et gitt steg i prosessen.
    * Ulemper: Fortsatt litt tregt å laste hele frontend og alt som skjer der. Potensielt en ekstrem omveltning for frontend-koden.
    * Hvem bærer ulempene: Frontend-utviklerne.
3. Vi legger inn en ny datatype for HTML-filer som er grunnlaget for generert PDF. Frontend laster opp en slik fil på slutten av hvert prosess-steg (før den kaller `process/next`) med en statisk HTML av hele prosess-steget. Backend kan til slutt slå sammen `<body>`-tagene på flere sider og rendre hele resultatet som en PDF.
    * Fordeler: Går nok veldig mye kjappere, så vi kan nok støtte asynkron PDF med en gang (frontend kan laste opp HTML for kvitteringssiden som det siste den gjør før PDF-kjøring trigges). Rimelig enkelt å implementere for både frontend og backend. Støtte for layout overalt. Vi kan kanskje støtte dette i `PrintButton` direkte i nettleseren (men da bare for gjeldende prosess-steg).
    * Ulemper: Man stoler kanskje for mye på frontend. En bruker kan skrive om sin egen kvitterings-PDF ved å koble seg på requesten som lagrer data. (Dette er bare et problem om kvitterings-PDF trumfer datamodellen i hvilken som representerer sannheten). Vi må vaske filen for potensiell Javascript, fengsle inne PDF-generatoren (siden den må generere PDF basert på veldig utrygge data). Sikkerhetsaspektet.
    * Hvem bærer ulempene: Rettsvesenet og juristene?
4. Samme som nr 3, men istedenfor at brukerens nettleser laster opp denne filen, er det heller backend sin oppgave å kjøre node.js etter prosess-steget for å spørre frontend hva den ville vist frem som HTML-grunnlag for PDFen (og så laster backend opp disse dataene til plattform istedenfor).
    * Fordeler: Sikkerhetsaspektet blir løst?
    * Ulemper: Nå har vi egentlig duplisert forslag 1, men laget et mellomsteg som lager HTML fra frontend som _senere_ skal sendes til PDF-generatoren. :facepalm: Hvis alle requester for å hente instansdata må kjøres på nytt kan vi like godt bruke PDF-tjenesten til dette. Dette blir nok fort tregt igjen.
    * Hvem bærer ulempene: Frontend- og backendutviklere må dele byrden gjennom uhyggelig arkitektur.
5. Vi implementerer støtte for at backend leser layout (potensielt oppsummering-layout eller lager sin egen), leser datamodellen, genererer HTML som skal vises i PDF for hver side og komponent.
    * Fordeler: Går kjapt. Vi har nok støtte for mye av dette på backend allerede, siden layout og koblingen mellom layout og datamodell (og data i datamodellen) blir lest av expression-motoren.
    * Ulemper: Vi må duplisere tvilsomt mye av frontend-funksjonaliteten på backend. Dette blir plutselig komplisert når vi skal inn med nye komponenter (de må også få en backend-implementasjon). Tallformattering via `react-number-format` må implementeres noenlunde tilsvarende backend. 
    * Hvem bærer ulempene: Backend-utviklerne.
6. Istedenfor at backend leser layout og lager PDF ut fra den, støtter vi heller et eget templating-språk og gjør det mulig for app-utviklere å skrive sin egen HTML som blir til PDF.
    * Fordeler: Veldig tilpassingsdyktig PDF. Går like kjapt som nr 5.
    * Ulemper: Ingen auto-generert default? Dette kan fort gjøre ting vanskeligere for app-utviklere. Hvordan løse rep.grupper?
    * Hvem bærer ulempene: Backend-utviklerne og app-utviklere.
7. Vi skriver om hele backend til TypeScript heller, så kan vi dele kode mellom frontend og backend. :wink:

**Comment by mijohansen** [comment]
1. Nullalternativet mangler... det er å **generere PDF direkte fra Layoutfiler**. Tenker at det er naturlig at dette blir med. Selv om det er en forenkling å gå via HTML, som forsåvidt heller ikke er ett alternativ over. Ang. nullalternativet så gir det rom for å virkelig kunne bygge pene juridiske dokumenter basert på innsendte data i Altinn. 

2. Jeg tenker at dagens løsning som faktisk ligger der i dag og **bruker `org.apache.pdfbox`** på mange måter er min foretrukne måte å lage PDF-A på. Jeg tror også denne løsningen vil være den aller raskeste å få til å bli skikkelig produksjonsklar og ha mindre vedlikehold.

Jeg holder begge disse alternativene over screen-scraping og egentlig alle variantene over. Begge løsningene over er langt enklere og har egentlig bare en avhengighet til formlayout og andre ting som vi legger inn i appene. Den er også lynrask. Tidligere har jeg vel egentlig bare hatt live-preview når jeg har brukt den løsningen. Det vil også være enklere for en utvikler eller andre å editere en slik løsning, fordi vi stort sett kan lage live preview basert på det som ligger i appen.

Til slutt brukes ett argument rundt dobbelt vedlikehold, da må jeg bare kontre og si at jeg fortsatt tror PDF og dokumenter er såpass viktig for denne typen transaksjoner at jeg på ingen måte anser det som en second-class citizens, vi skal bygge tillit i befolkningen og hos tjenesteeiere. Vi bør klare å produsere dokumenter som er av en slik karakter at våre kunder og brukere kjenner igjen den solide merkevaren som vi faktisk forvalter. Disse PDF-ene skal leve i arkiver, saksbehandlingssystemer og innbokser lenge etter at vi er ferdig i arbeidslivet. Det samme gjelder ikke resten av koden vi skriver. Så la oss bare gjøre det skikkelig, med høyre hånd og med merkevaren i bakhodet.
