### ISSUE TITLE
Signature is still added even if code in IProcessTaskEnd crashes

### ISSUE THREAD

**Issue by bjorntore** [Altinn/app-lib-dotnet#643]
### Description of the bug

Hvis det er aktivert en IProcessTaskEnd-operasjon på signatur-steget, som feiler, vil signatur fortsatt bli opprettet, og dermed multipliseres flere ganger når man forsøker å gå videre til neste steg. Hvis man feiler flere ganger på process/next i IProcessTaskEnd vil valideringen trigges når det oppstår flere signaturer enn hva Max-count tillater.

DIBK kunne tenkt seg at siste signatur var gjeldende. Bør diskuteres.

### Steps To Reproduce

1. Ha en app med grunnleggende signering satt opp.
2. Legg til en IProcessTaskEnd implementasjon som blir kjørt når signeringssteget blir fullført. Kast en exception med vilje.
3. Sørg for at det finnes et dataelement av datatypen(e) som skal signeres, slik at vi har noe å signere på.
4. Kjør process/next med sign-action. Process/next bør feile, men du ender opp med et signeringobjekt likevel, og neste gang du kjører process/next med sign-action vil du få enda en signatur.

### Additional Information

Slack-samtale om issuet: https://altinn.slack.com/archives/CCQEQKGJD/p1714044845070929

**Comment by bjorntore** [comment]
I believe this will be solved by https://github.com/Altinn/app-lib-dotnet/issues/460. Will test when that is completed.

**Comment by bjorntore** [comment]
The change in #460 does indeed cause any existing signature object that has been generated by the current signature step to be deleted if another signature attempt is made.

The signature element will still be generated and exists until the next attempt is made. We are planning a bigger refactor of the app process engine in the fall, and might deal with that then.

**Comment by martinothamar** [comment]
Assuming this can be closed
