### ISSUE TITLE
Attachment: Extension in UPPERCASE fails upload

### ISSUE THREAD

**Issue by SimenRokaas** [Altinn/app-lib-dotnet#667]
### Description of the bug

Uploading somefile.png works. Uploading somefile.PNG (copy of the first file just with uppercase extenstion) fails. 

### Steps To Reproduce

Upload a file with uppercase extension in an upload component.

### Additional Information

Ref https://altinn.slack.com/archives/C02EJ9HKQA3/p1717138743868539
Branch: https://altinn.studio/repos/dsb/int-1017-personopplysninger/src/branch/master

**Comment by SimenRokaas** [comment]
Possible cause is the check against allowed extensions. This check should be case insensitive, so if "png" is allowed then all of "png", "PNG", "pNg" etc are also allowed.

**Comment by HauklandJ** [comment]
@SimenRokaas Unable to reproduce:

https://github.com/Altinn/app-lib-dotnet/assets/42615991/6bfc3958-db7a-4d76-9525-014019a4d511

**Comment by HauklandJ** [comment]
Reprodusert med DSB sin app.

**Comment by danielskovli** [comment]
Kan bekrefte at https://github.com/Altinn/app-lib-dotnet/pull/676 fikser problemet i DSB sin app:

![bilde](https://github.com/Altinn/app-lib-dotnet/assets/21328986/b76c591b-83e0-4e07-84d5-155084f0a980)

Men frontend bør også kanskje endre sin pattern matching med tanke på ikonet som vises.

**Comment by danielskovli** [comment]
The icon issue was fixed by this commit: https://github.com/Altinn/app-frontend-react/commit/9323eb2eb6c0bd5aae8f9d12513373048246c35b
