### ISSUE TITLE
Backend endepunkt for å hente data fra eksternt api

### ISSUE THREAD

**Issue by cammiida** [Altinn/app-lib-dotnet#698]

**Comment by danielskovli** [comment]
Jeg titta tilfeldigvis på koden i [feature/external-api](https://github.com/Altinn/app-lib-dotnet/tree/feature/external-api), og synes det ser veldig nice ut!

Eneste spørsmålet er om det betyr at dere landet på "ja, tjenesteeier må inn i C# og skrive kode?". Det virker jo veldig naturlig, men tidligere i prosessen var det et sterkt ønske om at alt skulle skje via Studio... 🤷

Grunnen til at jeg spør er at jeg i så fall er veldig interessert i hvordan Studio skal implementere wysiwyg editor for dette 😎
