### ISSUE TITLE
Add and delete sub-forms - backend

### ISSUE THREAD

**Issue by HauklandJ** [Altinn/app-lib-dotnet#707]
Add/use existing controller with PUT and DELETE for data elements, without having to use process next

**Comment by danielskovli** [comment]
Currently trying to reuse existing `DataController`. TBC

**Comment by danielskovli** [comment]
`DataController` seems up to the challenge here, but we need to adjust some logic that [currently disallows deletion of form data](https://github.com/Altinn/app-lib-dotnet/blob/cf1bbf50ead9193eb3129736cfc5fdfe12fef928/src/Altinn.App.Api/Controllers/DataController.cs#L574-L579).

It could perhaps be an idea to expand the `applicationmetadata.json` interface a little bit, allowing us to specify the following sub-form properties:
- Can users **add** items? Currently exposed as [showAddButton](https://github.com/Altinn/app-frontend-react/blob/937a17a3e8f70bd1242af25fbd49de937fa0b4f7/src/layout/SubForm/config.ts#L28) on the SubForm component
- Can users **delete** items? Currently exposed as [showDeleteButton](https://github.com/Altinn/app-frontend-react/blob/937a17a3e8f70bd1242af25fbd49de937fa0b4f7/src/layout/SubForm/config.ts#L29) on the SubForm component
- Should we do something with `minCount` and `maxCount` to make it smoother for this purpose? They still need to exist, but especially `maxCount` might not always be super useful
- Most likely we need to wrap these preferences in a property on the relevant `dataTypes` entires. The presence of this property would at the same time mark the data type as a "subform", which we could check for in the `DataController` logic 

Advantages of moving the add/delete preferences to applicationmetadata.json is that the backend has a better grasp on the configuration, without needing to parse layout files. Disadvantages are possibly a more complicated `SubForm` implementation 🤷

**Comment by danielskovli** [comment]
After some internal discussions, it seems that we need to keep the "show add/delete button" config in the layout files, because we most likely want to support expressions in those values at some point.

How the server should be kept in sync here though, is unknown. Disallowing the add/delete buttons is only half the solution, the server also needs to refuse the associated REST calls.

Additionally we likely still want to tag the model/datatype with something in `applicationmetadata.json`, so the server can keep it's legacy "don't delete form data" for non-subform data types.

**Comment by danielskovli** [comment]
This has been implemented as properties in [Storage.Interface.Models.ApplicationLogic](https://github.com/Altinn/altinn-storage/blob/c67a0dbf623c1fe5371e1409a73e0e4d648f1342/src/Storage.Interface/Models/ApplicationLogic.cs#L43-L55) and corresponding checks  in [Altinn.App.Api.Controllers.DataController](https://github.com/Altinn/app-lib-dotnet/blob/ad56781b060608a61ffd7b70e806da626b22a129/src/Altinn.App.Api/Controllers/DataController.cs) [[1](https://github.com/Altinn/app-lib-dotnet/blob/ad56781b060608a61ffd7b70e806da626b22a129/src/Altinn.App.Api/Controllers/DataController.cs#L169), [2](https://github.com/Altinn/app-lib-dotnet/blob/ad56781b060608a61ffd7b70e806da626b22a129/src/Altinn.App.Api/Controllers/DataController.cs#L576)].

Needs additional unit testing and a general brainstorm re implementation of access control. Inspiration was taken from https://github.com/Altinn/app-lib-dotnet/pull/671.

**Comment by danielskovli** [comment]
Implemented. Could do with a review.

**Comment by danielskovli** [comment]
After a quick review session today, there's an open-ended question for @RonnyB71: Can this be solved in the authorization layer (policy.xml)? It doesn't seem like it to me, but worth discussing.

Specifically the [Storage.Interface.Models.ApplicationLogic](https://github.com/Altinn/altinn-storage/blob/c67a0dbf623c1fe5371e1409a73e0e4d648f1342/src/Storage.Interface/Models/ApplicationLogic.cs#L43-L55) part of the implementation -- the "can the user add and/or delete sub-form records" permission logic.

Leaving this issue open until the implementation has been discussed.

**Comment by danielskovli** [comment]
This has been implemented as proposed in Altinn.Storage now.
