### ISSUE TITLE
Populere applicationMetadata med `externalApiIds`

### ISSUE THREAD

**Issue by cammiida** [Altinn/app-lib-dotnet#736]
Uttrykksmotoren må ha hentet all dataen den potensielt trenger på forhånd slik som det er satt opp i dag. For å støtte `externalApi` i uttrykk må den derfor vite alle `id`-ene til de eksterne API-ene på forhånd. Dette kan støttes gjennom å legge det til på `applicationMetadata` fra backend fram til vi eventuelt endrer på uttrykksmotoren.

**Comment by HauklandJ** [comment]
Does not behave as I think was the goal. 
Reproducable:

Apis:

- ExternalApi : IExternalApiClient { Id = "testId" ...}
- AnotherExternalApi : IExternalApiClient { Id = "anotherId" ...} 

Layout:
```
{
  "id": "Tekst-Fra-Eksternt-Api",
  "type": "Text",
  "textResourceBindings": {
    "title": "Eksternt api"
  },
  "value": [
    "externalApi",
    "testId",
    "details[0].id"
  ],
  "direction": "vertical",
  "grid": {
    "xs": 6
  }
},
```

applicationMetadata:
- nothing

Network calls:

http://local.altinn.cloud/ttd/component-library/instances/510003/be051523-b136-4a72-8b38-7c289738fae1/api/external/testId


Note that only the externalApi with the id as in the layout was fetched.

**Comment by cammiida** [comment]
Solution changed, so not relevant any more.
