### ISSUE TITLE
dataValues are not set if the user does not make any changes before sending in

### ISSUE THREAD

**Issue by violaguttorm** [Altinn/app-lib-dotnet#780]
### Description of the bug

The `dataValues` fields are not set in an Instance if the user never makes any changes, but just clicks through the form and sends it in. We prefill some data, which means that occasionally a form might be filled correctly from the start and the user could just send it in, but we rely on these `dataValues` to correctly route the data to us. 

### Steps To Reproduce

1. Use `IInstantiationProcessor` to prefill data that can be a correct form in a new Instance. 
2. Send this in. 
3. Observe that the `dataValues` fields have not been set.

**Comment by martinothamar** [comment]
Was not able to reproduce this. I have an app implementing an `IInstantiationProcessor` and created some `dataFields` in `applicationmetadata.json` (I think this is what was discussed in the Slack thread). As I instantiate the `dataValues` are filled in. They are also there after sending in the form.

Does it depend on _how_ it is instantiated? I was doing this through the normal frontend

**Comment by violaguttorm** [comment]
Wait. Sorry, I actually forgot something important before reporting in. We actually prefill data in DataProcessing (`IDataProcessor -> DataProcessRead`) now (with a check to see if it has succeeded earlier to not double up). We do this since it's called anyway and we want the app to try again if the instance is opened again if the prefill failed earlier. 

That might be the cause? If so, is there a way I can manually fill these values in? (Or maybe just make the call within `IInstantiationProcessor` too if that works when you test? 😅) 

If relevant I can at least say that the data we filll into `dataFields` in `applicationmetadata.json` is data that the prefill fetched, so it didn't exist before instantiation ran.

**Comment by martinothamar** [comment]
Yeah `IDataProcessor` is never called if the instance is only instantiated I think, so if you _only_ rely on `IDataProcessor` then that explains the issue

**Comment by martinothamar** [comment]
Is `brg/rrh-innrapportering` the right app? If the issue is reproducible there (while also prefilling from `IInstantiationProcessor`) then I can probably debug it

**Comment by violaguttorm** [comment]
I tried putting Instantiation in `IInstantiationProcessor` and that fixed it. Case can be closed. Thank you for your time.

**Comment by ivarne** [comment]
I think the issue is that we don't update data values if you use a multipart request to initialise the instance and data elements.

 https://github.com/Altinn/app-lib-dotnet/blob/71b129f76643177bf0a8a4a9ac5aded34beec17a/src/Altinn.App.Api/Controllers/InstancesController.cs#L1157-L1158

**Comment by martinothamar** [comment]
`dataFields` and `dataValues` works in this case also, presumably because the `IProcessTaskInitializer` is running `UpdateDataValuesOnInstance`. That probably means we are running the processor hook twice though
