### ISSUE TITLE
Option to add a watermark on the generated PDF receipts

### ISSUE THREAD

**Issue by RonnyB71** [Altinn/app-lib-dotnet#787]
### Description

There is a need to add a watermark stamp on the generated PDF receipts to ensure that the PDF is actually generated after submitting the form. "Clever" users have used the build in print preview to fake a form being submitted to avoid payment steps later in the process. The case manager in the municipalities use the watermark as part of their routine and we should continue to support this feature from Altinn 2.

The watermark itself is basically a text value including date/time for when the PDF was generated as well as a reference id provided by the service owner.

The solution should be dynamic in terms of what values goes into the watermark allowing the application developers to construct the value based on date/time, values from the data model and/or instance metadata.

### Additional Information
This issue should be considered i relation to https://github.com/Altinn/app-frontend-react/issues/1805, and maybe allow for the inclusion of a "not valid" watermark if the PDF is generated before the final data submission.

**Example image showing watermarks in red**
![image](https://github.com/Altinn/app-lib-dotnet/assets/5430430/14335ac2-179a-4225-aa3d-cdf0d3ac328e)

### Design
Component : https://www.figma.com/design/aECTVzeAa3sJDucjYWQuUQ/Oppsummering-og-PDF?node-id=966-190399&t=1JdATXK1BkP2v3qF-4

Example: https://www.figma.com/design/aECTVzeAa3sJDucjYWQuUQ/Oppsummering-og-PDF?node-id=1081-140542&t=1JdATXK1BkP2v3qF-4

### Acceptance Criterias
- [x] Given that you enable watermark on the PDF, when you **don't** implement a custom watermark prover then we should return date, time and Altinn archive reference. 
- [ ] Given that you need a custom watermark text, when you implement a custom watermark provider then you should get the custom text returned from the watermark provider.
- [x] Given that you are on any page, when you show the PDF then the watermark should be printed in the footer area.
- [x] Given that you enable watermark, when you see show the PDF, then the watermark should stand out (ref. the design)
- [ ] Given that the PDF is generated before the data is complete, when you preview the PDF, then the watermark should show a language specific text for example in Norwegian "Forhåndsvisning" by default. 
- [ ] Given that the service owner would like their own text instead of the default, it should be an option to override the text with a specified text resource.

**Comment by Edavda** [comment]
Komponent: https://www.figma.com/design/aECTVzeAa3sJDucjYWQuUQ/Oppsummering-og-PDF?node-id=966-190399&t=1JdATXK1BkP2v3qF-4
