### ISSUE TITLE
Birth date validates immediately after you start to type a number.

### ISSUE THREAD

**Issue by Janingetjosvoll** [Altinn/app-lib-dotnet#808]
### Description of the bug

If you not choose the calendar, but choose to fill in the date number by number, you will get an error message once you start typing a number. There should either be a delay after every number is typed before the field is validated, or the field should not be validated until you have filled in all six numbers.

### Steps To Reproduce

![image](https://github.com/user-attachments/assets/a18caa95-8b4a-4659-9109-b2b63eb9057f)

**Comment by hanneline** [comment]
Dette gjelder også for årsregnskap. ![Image](https://github.com/user-attachments/assets/5f9518be-beda-4d4a-bc00-bd143623d38c)

Det er lite brukervennlig at bruker får feilmelding mens man fortsatt skriver i feltet, og man følger formatet DD.MM.YYYY, og ikke har skrevet noe feil. 
Feilmelding bør komme når man forlater feltet, eller man faktisk skriver noe som er feil (feks skriver 13 i MM).

**Comment by lmplmplmp** [comment]
Hei! Jeg har implementert en kontrollsjekk for kontrollsiffer i norske personnummer i skjemaet "Informasjon om jegerprøveinstruktør". Slik fungerer sjekken: Først kontrollerer jeg om en streng inneholder minst 11 sifre. Deretter trekker jeg ut de første 11 tegnene og bruker Regex.IsMatch til å bekrefte at de består kun av tall. Problemet er at det fortsatt dukker opp en feilmelding på det første sifferet. Responsen gir kode 200, men jeg mistenker at problemet kan skyldes en cross-origin policy. Se vedlagt bilde for detaljer![Image](https://github.com/user-attachments/assets/f80db285-7eff-4ad0-a0b4-1b7b2c96c7d1)

**Comment by lmplmplmp** [comment]
Midlertidig løsning:     "saveWhileTyping": 800 or  "saveWhileTyping": 1000 da for kunde tid til å skrive inn 11 siffer før feil kommer opp.

**Comment by hanneline** [comment]
@lmplmplmp DatePicker har ikke saveWhileTyping, så den kunne vi ikke bruke på datofeltene. Men de har kommet med ny implementering av DatePicker, der vi ikke får denne feilen.

**Comment by RonnyB71** [comment]
Closing, fixed by the new date picker implementation.
