### ISSUE TITLE
Implement the designed `ICorrespondenceClient`

### ISSUE THREAD

**Issue by martinothamar** [Altinn/app-lib-dotnet#826]
Implement `ICorrespondenceClient` as defined

## Acceptance criteria

- [x] The client implementation is a sealed internal class
~~It uses an internal variant of the `IMaskinportenClient`~~ 
- [x] It has robust error handling and telemetry
- [x] It can be used from within an Altinn app (`Altinn.App.Core`)

**Comment by danielskovli** [comment]
The acceptance criteria for using an _internal_ variant of `IMaskinportenClient` I believe is no longer desired. In either case, that's not how the client has currently been implemented.

**Comment by martinothamar** [comment]
agreed!
