### ISSUE TITLE
Implement internal variant of `IMaskinportenClient`

### ISSUE THREAD

**Issue by martinothamar** [Altinn/app-lib-dotnet#849]
We are going to end up with running 2 variants of the `IMaskinportenClient` - 1 using the custom client/scopes defined by the app owner in Studio, and 1 internal client with some built in scopes for operations that the app needs to do. Related issue: https://github.com/Altinn/app-lib-dotnet/issues/813

## Acceptance criteria

- [x] It is possible to request both the public and internal variant from DI
- [x] Same test coverage for both clients
- [x] Internal logic should be mostly the same (apart from configuration, since configuration should be different)
- [x] Telemetry makes it clear which client is making the requests

**Comment by RonnyB71** [comment]
Closing as this will be fixed with an internal authentiaction

**Comment by danielskovli** [comment]
Just for posterity: We ended up keeping this internal variant of the MaskinportenClient after all. The specific use-case @RonnyB71  was referring to will most likely be solved with an internal token from the authentication api.

However, we felt that the app itself may very well need its own way to authenticate with Maskinporten in the (near) future, so this internal client implementation lives on.
