### ISSUE TITLE
Expose HTTP codes and Problemdetails from PersonLookup and OrganisationLookup

### ISSUE THREAD

**Issue by cammiida** [Altinn/app-lib-dotnet#913]
### Description

To show correct error messages in the person lookup component, the frontend needs to know what went wrong.

**Comment by HauklandJ** [comment]
@martinothamar should we use specific http status codes, problemdetails, both? Consistency for sluttbruker is key here

**Comment by martinothamar** [comment]
From what I've seen we commonly use both.
Here for example: https://github.com/Altinn/app-lib-dotnet/blob/ad4193e0f318b07eb1f487df6d2dffd8b356b4f8/src/Altinn.App.Api/Controllers/DataController.cs#L1278-L1283

https://github.com/Altinn/app-lib-dotnet/blob/ad4193e0f318b07eb1f487df6d2dffd8b356b4f8/src/Altinn.App.Api/Controllers/DataController.cs#L680

We also have a result filter that enriches the current trace with `ProblemDetails` info, so it would be nice to standardize on that: https://github.com/Altinn/app-lib-dotnet/blob/ad4193e0f318b07eb1f487df6d2dffd8b356b4f8/src/Altinn.App.Api/Infrastructure/Middleware/TelemetryEnrichingResultFilter.cs#L10-L18
