### ISSUE TITLE
Support for multipart upload of binary data in DataController

### ISSUE THREAD

**Issue by tjololo** [Altinn/app-lib-dotnet#96]
### Description of the bug

DataController is checking if the request header "Content-Disposition" is set. This header should not be part of the request but in the subparts of a multipart request instead.
The check in Altinn.Core.Api is done here: https://github.com/Altinn/app-lib-dotnet/blob/v6.0.0/src/Altinn.App.Api/Controllers/DataController.cs#L699

The HttpRequest is also sent down to DataClient that also seems to misuse the header.

The api should not force clients to send http requests not adhering to the http standard

### Steps To Reproduce

1. Create an altinn3 application
2. Try to upload an attachment without specifying Content-Disposition in the requestheaders, this is a valid http request
3. Controller returns error

**Comment by SandGrainOne** [comment]
We have the same issue in Storage, but Storage doesn't force the invalid use of Content-Disposition as a request header in the same way. There are also support for a multipart request with Content-Disposition as a section header. Still created an issue: https://github.com/Altinn/altinn-storage/issues/102

Another issue you consider looking into here is how we've allowed the original HttpRequest to flow through all application layers and into the DataClient.

**Comment by RonnyB71** [comment]
cc: @FinnurO

**Comment by tjololo** [comment]
Renaming this isse to "Support for multipart upload of binary data in DataController". As it seems Content-DIsposition is set when using StreamContent or ByteArrayContent.

Tested with a simple client that uploads xml through StreamContent

Client code:
```csharp
public async Task<string> ProcessUploadXml(string instanceId, byte[] attachment, string filename, CancellationToken ct)
{
    var uri = $"{_baseUri}/{_appUri}/instances/501337/{instanceId}/data?dataType=attachment";
    using (var content = new StreamContent(new MemoryStream(attachment)))
    {
        content.Headers.ContentType = new MediaTypeHeaderValue("application/xml");
        content.Headers.ContentDisposition = ContentDispositionHeaderValue.Parse($"attachment; filename=\"{filename}\"");
        var httppRequest = new HttpRequestMessage(HttpMethod.Post, uri);
        httppRequest.Content = content;
        var res = await _client.SendAsync(httppRequest);
        if (!res.IsSuccessStatusCode)
        {
            _logger.LogError("Upload to {URI} failed with statuscode: {StatusCode} content: {Response}", uri,res.StatusCode, await res.Content.ReadAsStringAsync());
            throw new Exception("upload failed");
        }

        var responseConrtent = await res.Content.ReadAsStringAsync();
        return responseConrtent;
    }
}
```
Headers logged on the server side:
```console
      Connection: close
      Host: local.altinn.cloud
      Authorization: Bearer ##omitted##
      Content-Type: application/xml
      Content-Length: 33
      X-Real-IP: 172.18.0.1
      X-Forwarded-For: 172.18.0.1
      Content-Disposition: attachment; filename="demo.xml"

```

**Comment by tjololo** [comment]
Multipart not supported today and Content-Disposition usage is ok. Support for multipart not requested at this moment. Closing with won't fix.
